select case when I18ITM.NME is null then ITM10.NME else I18ITM.NME end as ITM10NME,
TXCT24.IID as TXCT24IID, TXCT24.NME as TXCT24NME, TXCT24.AGRT as TXCT24AGRT,
DBCR33.NME as DBCR33NME, DBCR33.IID as DBCR33IID, ITM10.IID as ITM10IID, ITMPRI.PRICT, ITMPRI.PRI, ITMPRI.UNST
from :TITMPRI as ITMPRI 
join :TITM as ITM10 on ITMPRI.ITM=ITM10.IID
join SESEL as SELR23 on ITM10.SELR=SELR23.DBCR
join DBCR as DBCR33 on ITM10.SELR=DBCR33.IID
left join TXCT as TXCT24 on TXCT24.IID=ITM10.TXCT
left join (select NME, HASNM from :TI18ITM where HASNM=:ITMID and LNG=':LNG') as I18ITM on I18ITM.HASNM=ITM10.IID
where ITMPRI.PRICT:PRCATIDCOND and ITM=:ITMID;
