select case when I18ITM.NME is null then ITM10.NME else I18ITM.NME end as ITM10NME,
:TXCTAL.IID as :TXCTALIID, :TXCTAL.NME as :TXCTALNME, :TXCTAL.AGRT as :TXCTALAGRT,
ITM10.IID as ITM10IID, ITMPRI.PRICT, ITMPRI.PRI, ITMPRI.UNST
from :TITMPRI as ITMPRI 
join :TITM as ITM10 on ITMPRI.ITM=ITM10.IID
left join TXCT as :TXCTAL on :TXCTAL.IID=ITM10.TXCT
left join (select NME, HASNM from :TI18ITM where HASNM=:ITMID and LNG=':LNG') as I18ITM on I18ITM.HASNM=ITM10.IID
where ITM=:ITMID and PRICT=:PRICTID;
