select TYP, ITMID, NME, IMAGEURL, SPECIFICINLIST, PRI, PREVIOUSPRI, QUAN, DETAILSMETHOD
from (
  select TYP, ITMID, NME, IMAGEURL, SPECIFICINLIST, PRI, PREVIOUSPRI, QUAN, DETAILSMETHOD
  from ITLIST where QUAN>0 and TYP=:ITTYP :WHEREADD
 ) as ITALL
join (select distinct ITM as ITINCAT from :TITCAT where ITSCATALOG:CATALOGFILTER) as ITINCATALL on ITINCATALL.ITINCAT=ITALL.ITMID
