select TYP, ITALL.ITMID as ITMID, IMAGEURL, PRI, PREVIOUSPRI, QUAN, DETAILSMETHOD,
  case when I18SPECIFICINLIST.NME is null then ITALL.NME else I18SPECIFICINLIST.NME end as NME,
  case when I18SPECIFICINLIST.SPECIFICINLIST is null then ITALL.SPECIFICINLIST else I18SPECIFICINLIST.SPECIFICINLIST end as SPECIFICINLIST
from (
  select TYP, ITMID, NME, IMAGEURL, SPECIFICINLIST, PRI, PREVIOUSPRI, QUAN, DETAILSMETHOD
  from ITLIST
  where QUAN>0 and TYP=:ITTYP :WHEREADD
 ) as ITALL
join (
  select distinct ITM as ITINCAT from :TITCAT where ITSCATALOG:CATALOGFILTER
 ) as ITINCATALL on ITINCATALL.ITINCAT=ITALL.ITMID
left join (
  select NME, SPECIFICINLIST, ITMID from I18SPECIFICINLIST  where TYP=:ITTYP and LNG=':LNG'
 ) as I18SPECIFICINLIST on I18SPECIFICINLIST.ITMID=ITALL.ITMID
