select IID, TYP, ITID, NME, IMG, SPECS, PRI, PRIPR, QUAN, DETMT
from (
  select IID, TYP, ITID, NME, IMG, SPECS, PRI, PRIPR, QUAN, DETMT
  from ITLIST where QUAN>0 and TYP=:ITTYP :WHEREADD
) as ITALL
join (select distinct ITM as ITINCAT from :TITCAT where CATL:FLTCAT) as ITINCATALL on ITINCATALL.ITINCAT=ITALL.ITID
