select ITSPEC.VER as VER, ITSPEC.LNG2 as LNG2, ITM.IID as ITMIID, ITSPEC.LNG1 as LNG1,
case when I18IT.NME is null then ITM.NME else I18IT.NME end as ITMNME,
case when I18CHOOSEABLESPECIFICS.NME is not null then I18CHOOSEABLESPECIFICS.NME when I18UOM.NME is not null then I18UOM.NME else ITSPEC.STR1 end as STR1,
case when I18ITMSPGR.NME is null then GRP.NME else I18ITMSPGR.NME end as GRPNME,
case when I18ITMSPF.NME is null then SPECIFICS.NME else I18ITMSPF.NME end as SPECIFICSNME,
ITSPEC.NUM1 as NUM1, ITSPEC.STR3 as STR3, ITSPEC.STR2 as STR2,
ITSPEC.NUM2 as NUM2, ITSPEC.STR4 as STR4, TEMPLATEDETAIL.HTMLT as TEMPLATEDETAILHTMLT,
TEMPLATEDETAIL.IID as TEMPLATEDETAILIID, TEMPLATESTART.HTMLT as TEMPLATESTARTHTMLT, TEMPLATESTART.IID as TEMPLATESTARTIID,
TEMPLATEEND.HTMLT as TEMPLATEENDHTMLT, TEMPLATEEND.IID as TEMPLATEENDIID, GRP.IID as GRPIID,
SPECIFICS.ISSHOWINLIST as SPECIFICSISSHOWINLIST, SPECIFICS.IID as SPECIFICSIID, SPECIFICS.TYP as SPECIFICSTYP, TEMPHTML.HTMLT as TEMPHTMLHTMLT, TEMPHTML.IID as TEMPHTMLIID
from :TITSPEC as ITSPEC
left join :TITM as ITM on ITSPEC.ITM=ITM.IID
left join ITMSP as SPECIFICS on ITSPEC.SPEC=SPECIFICS.IID
left join ITMSPGR as GRP on SPECIFICS.GRP=GRP.IID
left join HTMLT as TEMPLATEDETAIL on GRP.TEMPLATEDETAIL=TEMPLATEDETAIL.IID
left join HTMLT as TEMPLATESTART on GRP.TEMPLATESTART=TEMPLATESTART.IID
left join HTMLT as TEMPLATEEND on GRP.TEMPLATEEND=TEMPLATEEND.IID
left join HTMLT as TEMPHTML on SPECIFICS.TEMPHTML=TEMPHTML.IID
left join (select NME, HASNM from :T18NIT where HASNM=:ITMID and LNG=':LNG') as I18IT on I18IT.HASNM=ITM.IID
left join (select NME, HASNM from I18ITMSPF where LNG=':LNG') as I18ITMSPF on I18ITMSPF.HASNM=SPECIFICS.IID
left join (select NME, HASNM from I18ITMSPGR where LNG=':LNG') as I18ITMSPGR on I18ITMSPGR.HASNM=GRP.IID
left join (select NME, HASNM from I18CHOOSEABLESPECIFICS where LNG=':LNG') as I18CHOOSEABLESPECIFICS on I18CHOOSEABLESPECIFICS.HASNM=ITSPEC.LNG1 and SPECIFICS.TYP=9
left join (select NME, HASNM from I18UOM where LNG=':LNG') as I18UOM on I18UOM.HASNM=ITSPEC.LNG2 and (SPECIFICS.TYP=1 or SPECIFICS.TYP=2)
where ITSPEC.ITM=:ITMID order by SPECIFICS.ITSINDEX;
