select ITMSPF.VER, ITMSPF.LNG2, ITMSPF.LNG1, ITMSPF.NUM1, ITMSPF.STR3, ITMSPF.STR2, ITMSPF.NUM2, ITMSPF.STR4,
case when I18CHOSP.NME is not null then I18CHOSP.NME when I18UOM.NME is not null then I18UOM.NME else ITMSPF.STR1 end as STR1,
ITM10.IID as ITM10IID, case when I18IT.NME is null then ITM10.NME else I18IT.NME end as ITM10NME,
SPEC11.INLST as SPEC11INLST, SPEC11.IID as SPEC11IID, SPEC11.TYP as SPEC11TYP,
case when I18ITMSP.NME is null then SPEC11.NME else I18ITMSP.NME end as SPEC11NME,
GRP24.IID as GRP24IID, case when I18ITMSPGR.NME is null then GRP24.NME else I18ITMSPGR.NME end as GRP24NME,
HTMT25.VAL as HTMT25VAL, HTMT25.IID as HTMT25IID, TMPLD35.VAL as TMPLD35VAL, TMPLD35.IID as TMPLD35IID,
TMPLS36.VAL as TMPLS36VAL, TMPLS36.IID as TMPLS36IID, TMPLE38.VAL as TMPLE38VAL, TMPLE38.IID as TMPLE38IID
from :TITSPEC as ITMSPF
left join :TITM as ITM10 on ITMSPF.ITM=ITM10.IID
left join ITMSP as SPEC11 on ITMSPF.SPEC=SPEC11.IID
left join ITMSPGR as GRP24 on SPEC11.GRP=GRP24.IID
left join HTMLT as HTMT25 on SPEC11.HTMT=HTMT25.IID
left join HTMLT as TMPLD35 on GRP24.TMPLD=TMPLD35.IID
left join HTMLT as TMPLS36 on GRP24.TMPLS=TMPLS36.IID
left join HTMLT as TMPLE38 on GRP24.TMPLE=TMPLE38.IID
left join (select NME, HASNM from :T18NIT where HASNM=:ITMID and LNG=':LNG') as I18IT on I18IT.HASNM=ITM10.IID
left join (select NME, HASNM from I18ITMSP where LNG=':LNG') as I18ITMSP on I18ITMSP.HASNM=SPEC11.IID
left join (select NME, HASNM from I18ITMSPGR where LNG=':LNG') as I18ITMSPGR on I18ITMSPGR.HASNM=GRP24.IID
left join (select NME, HASNM from I18CHOSP where LNG=':LNG') as I18CHOSP on I18CHOSP.HASNM=ITMSPF.LNG1 and SPEC11.TYP=9
left join (select NME, HASNM from I18UOM where LNG=':LNG') as I18UOM on I18UOM.HASNM=ITMSPF.LNG2 and (SPEC11.TYP=1 or SPEC11.TYP=2)
where ITMSPF.ITM=:ITMID order by SPEC11.IDX;
