select BLTY, EID, DAT, SRID, SRTY, ACC, SUBACC, TOT, ISDEBT, CORACC, CRACNM, CRACNMB, CRSAC, UNIDET.DSCR from
( select ENTR.IID as EID, DAT, SRID, SRTY, ACDB as ACC, SADNM as SUBACC, DEBT as TOT, 1 as ISDEBT,
  ACCR as CORACC, ACNT.NME as CRACNM, ACNT.NMBR as CRACNMB, SACNM as CRSAC, ENTR.DSCR
  from ENTR
  left join ACNT on ENTR.ACCR=ACNT.IID
  where ACDB=':ACCID' :SADNM and DAT>=:DT1 and DAT<=:DT2
union all
  select ENTR.IID as EID, DAT, SRID, SRTY, ACCR as ACC, SACNM as SUBACC, CRED as TOT, 0 as ISDEBT,
  ACDB as CORACC, ACNT.NME as CRACNM, ACNT.NMBR as CRACNMB, SADNM as CRSAC, ENTR.DSCR
  from ENTR
  left join ACNT on ENTR.ACDB=ACNT.IID
  where ACCR=':ACCID' :SACNM and DAT>=:DT1 and DAT<=:DT2
) as UNIDET
join ACNT on UNIDET.ACC=ACNT.IID
order by DAT, EID;
