select 12 as SRTY, DAT, 'INVENTORY' as ACDB, ITMCT.NME as SADNM, ITMCT.IID as SADID, SUM(ITADLN.TOT) as DEBT,
null as ACCR, null as SACNM, null as SACID, 0.0 as CRED
from ITADLN
join ITM on ITM.IID=ITADLN.ITM
join ITMCT on ITMCT.IID=ITM.CAT
join ITMADD on ITMADD.IID=ITADLN.OWNR
where ITMADD.RVID is null and ITMADD.MDENR=0 :WHEAD
group by SRTY, DAT, ACDB, SADNM, SADID, ACCR, SACNM, SACID
