select 12 as SRTY, DAT, 'INVENTORY' as ACDB, ITMCT.NME as SADNM, ITMCT.IID as SADID, 1004 as SADTY, SUM(ITADLN.TOT) as DEBT,
null as ACCR, null as SACNM, null as SACID, null as SACTY, 0.0 as CRED
from ITADLN
join ITM on ITM.IID=ITADLN.ITM
join ITMCT on ITMCT.IID=ITM.CAT
join ITMADD on ITMADD.IID=ITADLN.OWNR
where ITADLN.RVID is null :WHEAD
group by SRTY, DAT, ACDB, SADNM, SADID, SADTY, ACCR, SACNM, SACID, SACTY
