select 7 as SRTY, PAYMFR.DAT, 'RECEIVABLE' as ACDB, DBCR.NME as SADNM, DBCR.IID as SADID, 1002 as SADTY, SAINTXLN.TOT as DEBT,
'SATAXPAY' as ACCR, TAX.NME as SACNM, TAX.IID as SACID, 1008 as SACTY, SAINTXLN.TOT as CRED
from PAYMFR
join SALINV on PAYMFR.INV=SALINV.IID
join SAINTXLN on SAINTXLN.OWNR=SALINV.IID
join TAX on TAX.IID=SAINTXLN.TAX
join DBCR on DBCR.IID=SALINV.DBCR
where SAINTXLN.RVID is null and SALINV.MDENR=1 and round(TOPA+PAYMFR.TOT,2)>=round(SALINV.TOT,2) :WHEAD
