select 5 as SRTY, PURINV.DAT, 'PAYABLE' as ACDB, DBCR.NME as SADNM, DBCR.IID as SADID, 1002 as SADTY, PAYMTO.TOT  as DEBT,
ACC as ACCR, SANM as SACNM, SAID as SACID, SATY as SACTY, PAYMTO.TOT as CRED
from PAYMTO
join PURINV on PURINV.IID=PAYMTO.INV
join DBCR on DBCR.IID=PURINV.DBCR
where PURINV.RVID is null and PURINV.MDENR=1 :WHEAD
