select 5 as SRTY, PURINV.DAT, 'PAYABLE' as ACDB, DBCR.NME as SADNM, DBCR.IID as SADID, PAYMTO.TOT  as DEBT,
ACC as ACCR, SANM as SACNM, SAID as SACID, PAYMTO.TOT as CRED
from PAYMTO
join PURINV on PURINV.IID=PAYMTO.INV
join DBCR on DBCR.IID=PURINV.DBCR
where PAYMTO.RVID is null and PURINV.RVID is null and PAYMTO.MDENR=0 and PURINV.MDENR=1 :WHEAD
