select 3 as SRTY, DAT, 'PREPTO' as ACDB, DBCR.NME as SADNM, DBCR.IID as SADID, TOT as DEBT,
ACC as ACCR, SANM as SACNM, SAID as SACID, TOT as CRED
from PREPTO
join DBCR on DBCR.IID=PREPTO.DBCR
where RVID is null and MDENR=0 :WHEAD
