select 3 as SRTY, DAT, 'PREPTO' as ACDB, DBCR.NME as SADNM, DBCR.IID as SADID, 1002 as SADTY, TOT as DEBT,
ACC as ACCR, SANM as SACNM, SAID as SACID, SATY as SACTY, TOT as CRED
from PREPTO
join DBCR on DBCR.IID=PREPTO.DBCR
where RVID is null :WHEAD
