select 4 as SRTY, PURINV.DAT, 'PAYABLE' as ACDB, DBCR.NME as SADNM, DBCR.IID as SADID, 1002 as SADTY,
case when PREPTO.TOT<PURINV.TOT then PREPTO.TOT else PURINV.TOT end as DEBT,
'PREPTO' as ACCR, DBCR.NME as SACNM, DBCR.IID as SACID, 1002 as SACTY,
case when PREPTO.TOT<PURINV.TOT then PREPTO.TOT else PURINV.TOT end as CRED
from PREPTO
join PURINV on PURINV.PREP=PREPTO.IID
join DBCR on DBCR.IID=PREPTO.DBCR
where PREPTO.RVID is null and PREPTO.MDENR=1 :WHEAD
