select 4 as SRTY, DAT, PUINSRLN.ACC as ACDB, PUINSRLN.SANM as SADNM, PUINSRLN.SAID as SADID, PUINSRLN.SATY as SADTY, SUM(PUINSRLN.SUBT) as DEBT,
'PAYABLE' as ACCR, DBCR.NME as SACNM, DBCR.IID as SACID, 1002 as SACTY, SUM(PUINSRLN.SUBT) as CRED
from PUINSRLN
join PURINV on PURINV.IID=PUINSRLN.OWNR
join DBCR on DBCR.IID=PURINV.DBCR
where PUINSRLN.RVID is null :WHEAD
group by SRTY, DAT, ACDB, SADNM, SADID, SADTY, ACCR, SACNM, SACID, SACTY
