select 4 as SRTY, PURINV.DAT, 'PAYABLE' as ACDB, DBCR.NME as SADNM, DBCR.IID as SADID,
case when PREPTO.TOT<PURINV.TOT then PREPTO.TOT else PURINV.TOT end as DEBT,
'PREPTO' as ACCR, DBCR.NME as SACNM, DBCR.IID as SACID,
case when PREPTO.TOT<PURINV.TOT then PREPTO.TOT else PURINV.TOT end as CRED
from PREPTO
join PURINV on PURINV.PREP=PREPTO.IID
join DBCR on DBCR.IID=PREPTO.DBCR
where PREPTO.RVID is null and PURINV.RVID is null and PREPTO.MDENR=1 and PURINV.MDENR=0 :WHEAD
