select 4 as SRTY, DAT, PUINSRLN.ACC as ACDB, PUINSRLN.SANM as SADNM, PUINSRLN.SAID as SADID, SUM(PUINSRLN.SUBT) as DEBT,
'PAYABLE' as ACCR, DBCR.NME as SACNM, DBCR.IID as SACID, SUM(PUINSRLN.SUBT) as CRED
from PUINSRLN
join PURINV on PURINV.IID=PUINSRLN.OWNR
join DBCR on DBCR.IID=PURINV.DBCR
where PURINV.RVID is null and PURINV.MDENR=0 :WHEAD
group by SRTY, DAT, ACDB, SADNM, SADID, ACCR, SACNM, SACID
