select 4 as SRTY, DAT, 'INVENTORY' as ACDB, ITMCT.NME as SADNM, ITMCT.IID as SADID, 1004 as SADTY, SUM(PUINGDLN.SUBT) as DEBT,
'PAYABLE' as ACCR, DBCR.NME as SACNM, DBCR.IID as SACID, 1002 as SACTY, SUM(PUINGDLN.SUBT) as CRED
from PUINGDLN
join ITM on ITM.IID=PUINGDLN.ITM
join ITMCT on ITMCT.IID=ITM.CAT
join PURINV on PURINV.IID=PUINGDLN.OWNR
join DBCR on DBCR.IID=PURINV.DBCR
where PUINGDLN.RVID is null :WHEAD
group by SRTY, DAT, ACDB, SADNM, SADID, SADTY, ACCR, SACNM, SACID, SACTY
