select 4 as SRTY, PURINV.DAT, 'SATAXRECV' as ACDB, TAX.NME as SADNM, TAX.IID as SADID, 1008 as SADTY, PUINTXLN.TOT as DEBT,
'PAYABLE' as ACCR, DBCR.NME as SACNM, DBCR.IID as SACID, 1002 as SACTY, PUINTXLN.TOT as CRED
from PUINTXLN
join TAX on TAX.IID=PUINTXLN.TAX
join PURINV on PURINV.IID=PUINTXLN.OWNR
join DBCR on DBCR.IID=PURINV.DBCR
where PUINTXLN.RVID is null :WHEAD
