select 4 as SRTY, PURINV.DAT, 'SATAXFR' as ACDB, TAX.NME as SADNM, TAX.IID as SADID, PUINTXLN.TOT as DEBT,
'PAYABLE' as ACCR, DBCR.NME as SACNM, DBCR.IID as SACID, PUINTXLN.TOT as CRED
from PUINTXLN
join TAX on TAX.IID=PUINTXLN.TAX
join PURINV on PURINV.IID=PUINTXLN.OWNR
join DBCR on DBCR.IID=PURINV.DBCR
where PURINV.RVID is null and PURINV.MDENR=0 :WHEAD
