select 8 as SRTY, PURRET.DAT, 'RETRECV' as ACDB, DBCR.NME as SADNM, DBCR.IID as SADID, PURTTXLN.TOT as DEBT,
'SATAXPAYRT' as ACCR, TAX.NME as SACNM, TAX.IID as SACID, PURTTXLN.TOT as CRED
from PURTTXLN
join TAX on TAX.IID=PURTTXLN.TAX
join PURRET on PURRET.IID=PURTTXLN.OWNR
join PURINV on PURINV.IID=PURRET.INV
join DBCR on DBCR.IID=PURINV.DBCR
where PURRET.RVID is null and PURRET.MDENR=0 :WHEAD
