select 6 as SRTY, SALINV.DAT, 'PREPFR' as ACDB, DBCR.NME as SADNM, DBCR.IID as SADID, 1002 as SADTY,
case when PREPFR.TOT<SALINV.TOT then PREPFR.TOT else SALINV.TOT end as DEBT,
'RECEIVABLE' as ACCR, DBCR.NME as SACNM, DBCR.IID as SACID, 1002 as SACTY,
case when PREPFR.TOT<SALINV.TOT then PREPFR.TOT else SALINV.TOT end as CRED
from PREPFR
join SALINV on SALINV.PREP=PREPFR.IID
join DBCR on DBCR.IID=PREPFR.DBCR
where PREPFR.RVID is null and PREPFR.MDENR=1 :WHEAD
