select 6 as SRTY, DAT, 'RECEIVABLE' as ACDB, DBCR.NME as SADNM, DBCR.IID as SADID, SUM(SAINGDLN.SUBT) as DEBT,
'GSALES' as ACCR, ITMCT.NME as SACNM, ITMCT.IID as SACID, SUM(SAINGDLN.SUBT) as CRED
from SAINGDLN
join ITM on ITM.IID=SAINGDLN.ITM
join ITMCT on ITMCT.IID=ITM.CAT
join SALINV on SALINV.IID=SAINGDLN.OWNR
join DBCR on DBCR.IID=SALINV.DBCR
where SALINV.RVID is null and SALINV.MDENR=0 :WHEAD
group by SRTY, DAT, ACDB, SADNM, SADID, ACCR, SACNM, SACID
