select 6 as SRTY, SALINV.DAT, 'PREPFR' as ACDB, DBCR.NME as SADNM, DBCR.IID as SADID,
case when PREPFR.TOT<SALINV.TOT then PREPFR.TOT else SALINV.TOT end as DEBT,
'RECEIVABLE' as ACCR, DBCR.NME as SACNM, DBCR.IID as SACID,
case when PREPFR.TOT<SALINV.TOT then PREPFR.TOT else SALINV.TOT end as CRED
from PREPFR
join SALINV on SALINV.PREP=PREPFR.IID
join DBCR on DBCR.IID=PREPFR.DBCR
where PREPFR.RVID is null and SALINV.RVID is null and PREPFR.MDENR=1 and SALINV.MDENR=0 :WHEAD
