select 6 as SRTY, DAT, 'COGS' as ACDB, ITMCT.NME as SADNM, ITMCT.IID as SADID, SUM(COGSENR.TOT) as DEBT,
'INVENTORY' as ACCR, ITMCT.NME as SACNM, ITMCT.IID as SACID, SUM(COGSENR.TOT) as CRED
from (select SOWID, ITM, TOT from COGSENR where SOWTY=4) as COGSENR
join SALINV on SALINV.IID=COGSENR.SOWID
join ITM on ITM.IID=COGSENR.ITM
join ITMCT on ITMCT.IID=ITM.CAT
where SALINV.RVID is null and SALINV.MDENR=0 :WHEAD
group by SRTY, DAT, ACDB, SADNM, SADID, ACCR, SACNM, SACID
