select 6 as SRTY, SALINV.DAT, 'RECEIVABLE' as ACDB, DBCR.NME as SADNM, DBCR.IID as SADID, 1002 as SADTY, SAINTXLN.TOT as DEBT,
'SATAXPAY' as ACCR, TAX.NME as SACNM, TAX.IID as SACID, 1008 as SACTY, SAINTXLN.TOT as CRED
from SAINTXLN
join TAX on TAX.IID=SAINTXLN.TAX
join SALINV on SALINV.IID=SAINTXLN.OWNR
join DBCR on DBCR.IID=SALINV.DBCR
where SAINTXLN.RVID is null :WHEAD
