select 9 as SRTY, SALRET.DAT, 'SATAXRECVRT' as ACDB, TAX.NME as SADNM, TAX.IID as SADID, 1008 as SADTY, SARTTXLN.TOT as DEBT,
'RETPAY' as ACCR, DBCR.NME as SACNM, DBCR.IID as SACID, 1002 as SACTY, SARTTXLN.TOT as CRED
from SARTTXLN
join TAX on TAX.IID=SARTTXLN.TAX
join SALRET on SALRET.IID=SARTTXLN.OWNR
join SALINV on SALINV.IID=SALRET.INV
join DBCR on DBCR.IID=SALINV.DBCR
where SARTTXLN.RVID is null :WHEAD
