select 9 as SRTY, SALRET.DAT, 'SATAXRECVRT' as ACDB, TAX.NME as SADNM, TAX.IID as SADID, SARTTXLN.TOT as DEBT,
'RETPAY' as ACCR, DBCR.NME as SACNM, DBCR.IID as SACID, SARTTXLN.TOT as CRED
from SARTTXLN
join TAX on TAX.IID=SARTTXLN.TAX
join SALRET on SALRET.IID=SARTTXLN.OWNR
join SALINV on SALINV.IID=SALRET.INV
join DBCR on DBCR.IID=SALINV.DBCR
where SALRET.RVID is null and SALRET.MDENR=0 :WHEAD
