select 9 as SRTY, SALRET.DAT, 'GRETURNS' as ACDB, ITMCT.NME as SADNM, ITMCT.IID as SADID, SUM(SARTLN.SUBT) as DEBT,
'RETPAY' as ACCR, DBCR.NME as SACNM, DBCR.IID as SACID, SUM(SARTLN.SUBT) as CRED
from SARTLN
join SAINGDLN on SAINGDLN.IID=SARTLN.INVL
join ITM on ITM.IID=SAINGDLN.ITM
join ITMCT on ITMCT.IID=ITM.CAT
join SALRET on SALRET.IID=SARTLN.OWNR
join SALINV on SALINV.IID=SALRET.INV
join DBCR on DBCR.IID=SALINV.DBCR
where SALRET.RVID is null and SALRET.MDENR=0 :WHEAD
group by SRTY, DAT, ACDB, SADNM, SADID, ACCR, SACNM, SACID
