select 15 as SRTY, DAT, WGLN.ACWGE as ACDB, EXPN.NME as SADNM, EXPN.IID as SADID, 1000 as SADTY, SUM(WGLN.GRWG-WGLN.TXEE) as DEBT,
'WAGEPAY' as ACCR, EMPCT.NME as SACNM, EMPCT.IID as SACID, 1009 as SACTY, SUM(WGLN.GRWG-WGLN.TXEE) as CRED
from WGLN
join WAGTY on WGLN.WGTY=WAGTY.IID
join EXPN on WAGTY.EXP=EXPN.IID
join WAGE on WAGE.IID=WGLN.OWNR
join EMPL on WAGE.EMPL=EMPL.IID
join EMPCT on EMPL.CAT=EMPCT.IID
where WGLN.RVID is null :WHEAD
group by SRTY, DAT, ACDB, SADNM, SADID, SADTY, ACCR, SACNM, SACID, SACTY
