select 2000 as SRTY, DAT, PUINGDLN.IID as IID, PURINV.IID as OWID, TOLF, ITLF
from PUINGDLN
join PURINV on PURINV.IID=PUINGDLN.OWNR
where PUINGDLN.RVID is null and MDENR=1 and ITLF>0 and PUINGDLN.DBOR=:DBOR and ITM=:ITM and UOM=:UOM
