select 2003 as SRTY, DAT, SARTLN.IID as IID, SALRET.IID as OWID, WRHP, ITLF,
case when TOLF=0.0 then SARTLN.SUBT else TOLF end as TOLF
from SARTLN
join SAINGDLN on SAINGDLN.IID=SARTLN.INVL
join SALRET on SALRET.IID=SARTLN.OWNR
where SARTLN.RVID is null and MDENR=1 and ITLF>0 and SARTLN.DBOR=:DBOR and ITM=:ITM and UOM=:UOM
