select SAINGDLN.IID as IID, SAINGDLN.TXFC as TXFC, ITM12.IID as ITM12IID, SAINGDLN.TDSC as TDSC, SAINGDLN.TOT as TOT,
SAINGDLN.SUBT as SUBT, SAINGDLN.PRI as PRI, SAINGDLN.TOTX as TOTX, SAINGDLN.QUAN as QUAN, SAINGDLN.TOFC as TOFC,
UOM15.IID as UOM15IID,
case when I18ITM.NME is null then ITM12.NME else I18ITM.NME  end as ITM12NME,
case when I18UOM.NME is null then UOM15.NME else I18UOM.NME  end as UOM15NME
from SAINGDLN
left join ITM as ITM12 on SAINGDLN.ITM=ITM12.IID
left join UOM as UOM15 on SAINGDLN.UOM=UOM15.IID
left join (select NME, HASNM from I18ITM where LNG=':LNG') as I18ITM on ITM12.IID=I18ITM.HASNM
left join (select NME, HASNM from I18UOM where LNG=':LNG') as I18UOM on UOM15.IID=I18UOM.HASNM
where SAINGDLN.RVID is null and SAINGDLN.OWNR=:OWNR;
