select SAINSRLN.IID as IID, SAINSRLN.TXFC as TXFC, ITM11.IID as ITM11IID, SAINSRLN.TDSC as TDSC, SAINSRLN.TOT as TOT,
SAINSRLN.SUBT as SUBT, SAINSRLN.PRI as PRI, SAINSRLN.TOTX as TOTX, SAINSRLN.QUAN as QUAN, SAINSRLN.TOFC as TOFC,
UOM15.IID as UOM15IID,
case when I18ITM.NME is null then ITM11.NME else I18ITM.NME  end as ITM11NME,
case when I18UOM.NME is null then UOM15.NME else I18UOM.NME  end as UOM15NME
from SAINSRLN
left join SRV as ITM11 on SAINSRLN.ITM=ITM11.IID
left join UOM as UOM15 on SAINSRLN.UOM=UOM15.IID
left join (select NME, HASNM from I18SRV where LNG=':LNG') as I18ITM on ITM11.IID=I18ITM.HASNM
left join (select NME, HASNM from I18UOM where LNG=':LNG') as I18UOM on UOM15.IID=I18UOM.HASNM
where SAINSRLN.RVID is null and SAINSRLN.OWNR=:OWNR;
