select ILID, TXCT as TXCTID, TAX as TAXID, TAX.NME as TAXNME, RATE, sum(TOTX) as TOTX, sum(TXFC) as TXFC
from
( select PURTLN.IID as ILID, PUINGDLN.TXCT, PURTLN.TOTX, PURTLN.TXFC from PURTLN
  join PUINGDLN on PUINGDLN.IID=PURTLN.INVL
  where PUINGDLN.TXCT is not null and PURTLN.RVID is null and PURTLN.OWNR=:INVID
) as ALLNS
join TXCT on TXCT.IID=TXCT
join TXCTLN on TXCTLN.OWNR=TXCT.IID
join TAX on TXCTLN.TAX=TAX.IID
group by ILID, TXCTID, TAXID, TAXNME, RATE;
