select TXCT as TXCTID, TAX as TAXID, TAX.NME as TAXNME, RATE, sum(SUBT) as SUBT, sum(SUFC) as SUFC
from
( select SAINGDLN.TXCT, SARTLN.SUBT, SARTLN.SUFC from SARTLN
  join SAINGDLN on SAINGDLN.IID=SARTLN.INVL
  where SAINGDLN.TXCT is not null and SARTLN.RVID is null and SARTLN.OWNR=:INVID
) as ALLNS
join TXCT on TXCT.IID=ALLNS.TXCT
join TXCTLN on TXCTLN.OWNR=TXCT.IID
join TAX on TXCTLN.TAX=TAX.IID
group by TXCTID, TAXID, TAXNME, RATE
order by TAXID;
