select ILID, TXCT as TXCTID, TAX as TAXID, TAX.NME as TAXNME, RATE, sum(TOTX) as TOTX, sum(TXFC) as TXFC
from
( select SARTLN.IID as ILID, SAINGDLN.TXCT, SARTLN.TOTX, SARTLN.TXFC from SARTLN
  join SAINGDLN on SAINGDLN.IID=SARTLN.INVL
  where SAINGDLN.TXCT is not null and SARTLN.RVID is null and SARTLN.OWNR=:INVID
) as ALLNS
join TXCT on TXCT.IID=TXCT
join TXCTLN on TXCTLN.OWNR=TXCT.IID
join TAX on TXCTLN.TAX=TAX.IID
group by ILID, TXCTID, TAXID, TAXNME, RATE;
